# -*- coding: utf-8 -*-
"""logging_server_py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OhAz7kCiD-W18mZ_UELMLputNNVpgDyi
"""

# run the following .py file to start a mcp server.
# Encapsulation: The database pool is now tied directly to the lifetime of the mcp server instance. If the server dies, the pool dies with it.
# No global state: You avoid modifying global-scope memory dynamically during runtime, which prevents a category of bugs where the pool might
# accidentally get overwritten or reset by another module.

import os
from typing import Dict, Any
from fastapi import FastAPI
from pydantic import BaseModel
from contextlib import asynccontextmanager
import psycopg
import psycopg_pool
import datetime

# --- Configuration (Centralized) ---
# Get DB_URI from environment or use a default/placeholder
DB_URI = os.getenv("DB_URI", "postgresql://user:password@localhost:5432/langgraph_db")

import os
import json
import logging
import sys
from contextlib import asynccontextmanager
from typing import Any, Dict, Optional
import psycopg_pool
from mcp.server.fastmcp import FastMCP

# CRITICAL FIX: Redirect logging to sys.stderr.
# Writing to sys.stdout will break the stdio JSON-RPC transport pipe used by MCP.
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    stream=sys.stderr
)
#Redirected Console Logs (stream=sys.stderr): I forced logging.basicConfig to send all text messages (like "Initializing database pool...") to
#  sys.stderr. This prevents raw text from leaking into sys.stdout, which is strictly reserved for JSON-RPC messages.

# FastMCP requires a dictionary so it can automatically format the final response into a valid JSON-RPC structure. log_event return

logger = logging.getLogger("mcp_logging_server")

DB_URI = os.getenv("DB_URI", "postgresql://user:password@localhost:5432/langgraph_db")

class LoggingServerDependencies:
    def __init__(self):
        self.pool: Optional[psycopg_pool.AsyncConnectionPool] = None

    @asynccontextmanager
    async def lifespan(self, server: FastMCP):
        logger.info("Initializing production database pool...")

        # Initialize connection pool with robust parameters
        self.pool = psycopg_pool.AsyncConnectionPool(
            conninfo=DB_URI,
            min_size=2,
            max_size=15,
            timeout=5.0,
            open=False
        )

        try:
            await self.pool.open()

            # Setup database tables and indexes safely
            async with self.pool.connection() as conn:
                async with conn.cursor() as cur:
                    await cur.execute(
                        """
                        CREATE TABLE IF NOT EXISTS logs (
                            id SERIAL PRIMARY KEY,
                            timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                            log_type VARCHAR(255) NOT NULL,
                            message TEXT NOT NULL,
                            details JSONB NOT NULL DEFAULT '{}'::jsonb
                        );
                        """
                    )
                    await cur.execute("CREATE INDEX IF NOT EXISTS idx_logs_log_type ON logs(log_type);")
                # psycopg pool handles autocommit differently depending on config.
                # Explicitly commit the schema generation.
                await conn.commit()

            logger.info("Database validation completed successfully.")
        except Exception as e:
            logger.critical(f"Database setup failure: {e}", exc_info=True)
            # Force termination if the application cannot initialize its core storage layer
            sys.exit(1)

        yield  # Hand over execution control to the running FastMCP engine

        # Shutdown sequence
        if self.pool:
            logger.info("De-allocating connection pool variables...")
            await self.pool.close()

# Initialize State and Instance
server_state = LoggingServerDependencies()
mcp = FastMCP("MCP Logging Server", lifespan=server_state.lifespan)

# This line of code instantiates your Model Context Protocol (MCP) server framework and registers your custom startup/shutdown lifecycle logic. [1]
# Here is the quick breakdown of its parameters:

# * FastMCP("MCP Logging Server"): This initializes a new instance of the FastMCP server framework. The string "MCP Logging Server" is the
#  human-readable name of your server, which will be visible in debugging tools or client UI dashboards. [2, 3, 4]
# * lifespan=server_state.lifespan: This registers your custom @asynccontextmanager function to the server engine.
#  It strictly commands FastMCP: "Before you start listening for incoming tool requests, execute the setup phase (opening the database pool).
#  When the server receives a shutdown command, execute the cleanup phase (closing the pool)." [5, 6]

# By assigning this configuration to the global variable mcp, you create the central registry where all future @mcp.tool() definitions are attached
#  and managed.
# Now that the server setup is fully explained, let me know if you would like to move on to the Docker deployment steps for your files, or if you
# want to look at adding Pydantic schemas to secure your log data structure!


@mcp.tool()
async def log_event(log_type: str, message: str, details: Optional[Dict[str, Any]] = None) -> dict:
    """Logs an operational system event to the central PostgreSQL database."""

    # Check pool validity safely
    if server_state.pool is None:
        return {"status": "error", "message": "Database pool unavailable."}

    sanitized_details = details if details is not None else {}

    try:
        # Request a healthy connection from the active pool
        async with server_state.pool.connection() as conn:
            async with conn.cursor() as cur:
                await cur.execute(
                    "INSERT INTO logs (log_type, message, details) VALUES (%s, %s, %s);",
                    (log_type, message, json.dumps(sanitized_details))
                )
            # Commit the transaction block safely
            await conn.commit()

        # FIX: Return a native dictionary object instead of stringified JSON.
        # FastMCP will natively format this into the proper JSON-RPC payload for utils.py.
        return {"status": "success", "message": "Log recorded."}

    except Exception as e:
        logger.error(f"Failed transaction execution: {e}", exc_info=True)
        return {"status": "error", "message": str(e)}

if __name__ == "__main__":
    mcp.run()

# Type checkers like PyRight or Mypy can now confirm that server_state.pool
#  is structured correctly.Proper Connection Pool Sizing (min_size/max_size): Keeping min_size=2 means incoming logs do not have to negotiate a
#   fresh handshake overhead on every call. Scaling to max_size=15 protects against concurrent database zzstarvation if multiple LLM agent chains
#    hammer the logger at the exact same millisecond.
#   ?? Database Performance Indexing: Added a production database index on log_type (idx_logs_log_type).
#    When your log table reaches millions of rows, searches filter instantly instead of causing full table scans.Structured Python Native
#    Logging: Replaced all arbitrary print() statements with Python's standard logging library module. This formats timestamp tracking outputs
#     seamlessly into modern cloud container platforms (like Docker, Kubernetes, AWS ECS, or GCP Cloud Run).Context Propagation (ctx): Added the
#      standard Context parameter to the FastMCP tool signature. This allows you to pass active debugging data back up to the calling LLM or
#      logging client seamlessly without breaking the schema contract.Are you going to be running this inside a container network like Docker,
#      or do you want to set up an asynchronous suite of unit tests using pytest-asyncio next?